### ISSUE TITLE
Collect qbeds into a common directory

### ISSUE THREAD

**Issue by allenyen** [nf-core/callingcards#2]
### Description of feature

Currently each analyzed sample gets its own directory and each contains the subdirectories fastqc, hops, picard, rseqc, and samtools. Since the qbed files are often times what we ultimately want, it can be helpful to collect the qbeds from all analyzed samples and place them all together to facilitate downloading or extracting for downstream analyses. My temporary solution is to find and copy the qbeds using `find /path/to/output_dir -iname '*.qbed' -exec cp {} /path/to/output_dir/qbeds`. 

Of course this creates duplicate files, it'd probably be more efficient to find the qbeds and create symlinks but haven't gotten that working yet.

**Comment by cmatKhan** [comment]
That assumes that the input samples are related -- it seems reasonable to keep all output grouped by sample in the pipeline and let the user deal with organizing it as they see fit
