### ISSUE TITLE
Figure out what to do with *_qc.tsv files

### ISSUE THREAD

**Issue by allenyen** [nf-core/callingcards#3]
### Description of feature

The `*_qc.tsv` file within `/output_dir/<sample>/hops/<sample>_qc.tsv` can be quite large. As a reference, a sample with 5M mapped reads has a 2.0GB `*_qc.tsv` file, while a sample with 78M reads is 32.9GB. With multiple samples, this can get quite large quickly. Would it be reasonable to remove this file upon successful completion of the pipeline? Or have a pipeline parameter to let the user choose if they want to keep it?

**Comment by cmatKhan** [comment]
I have a setting to turn off the production of these files, but it is on by default right now. I'll go ahead and turn it off.

 I'm also thinking now is that it is useful to split up the bams and the _qc files (if the user chooses to produce them) by chromosome. That keeps those files more manage-able, and will of course better parallelize and speed up the pipeline on big input.

The output qBed file would not be chunked, if I end up going with this method.

**Comment by cmatKhan** [comment]
This has been addressed in my fork -- I'll be pushing into this branch shortly:

https://github.com/cmatKhan/callingcards/tree/f3154107625d82ab68567b655d74f4d3d89b9de9

**Comment by cmatKhan** [comment]
this is addressed in the current `dev` branch
